version: "3.7"
services:
  gateway:
    build:
      context: docker/gateway
      dockerfile: develop/nginx/Dockerfile
    ports:
      - "8190:8190"
      - "8191:8191"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: docker/frontend
      dockerfile: develop/nginx/Dockerfile
    volumes:
      - ./frontend:/app
  api:
    build:
      context: docker/api
      dockerfile: develop/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: docker/api
      dockerfile: develop/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: docker/api
      dockerfile: develop/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./api:/app

  psql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
    volumes:
      - psql:/var/lib/postgresql/data

volumes:
  psql:

### Это для линукса. Лочим ip чтобы работать с xdebug
#networks:
#  default:
#    ipam:
#        driver: default
#        config:
#          - subnet: 172.22.0.0/16



