version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: develop/nginx/Dockerfile
    ports:
      - "8190:8190"
      - "8191:8191"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker
      dockerfile: develop/nginx/Dockerfile
    volumes:
      - ./frontend:/app
  api:
    build:
      context: api/docker
      dockerfile: develop/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: develop/php-fpm/Dockerfile
    volumes:
      - ./api:/app


