version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/ecom-gateway:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/ecom-frontend:${IMAGE_TAG}
    restart: always
  api:
    image: ${REGISTRY}/ecom-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/ecom-api-php-fpm:${IMAGE_TAG}
    restart: always

