version: "3.7"
services:
  gateway:
    build:
      context: ./gateway/docker/develop/nginx
    ports:
      - "8190:8190"
      - "8191:8191"
    depends_on:
      - frontend
      - api

  frontend:
    build:
        context: ./frontend/docker/develop/nginx
    volumes:
      - ./frontend:/app
  api:
    build:
      context: ./api/docker/develop/nginx
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: ./api/docker/develop/php-fpm
    volumes:
      - ./api:/app


