version: "3.7"
services:
  frontend:
    build:
        context: frontend/docker/develop/nginx
    ports:
      - "8090:80"
    volumes:
      - ./frontend:/app
  api:
    build:
      context: api/docker/develop/nginx
    ports:
      - "8091:80"
    volumes:
      - ./api:/app
  api-php-fpm:
    build:
      context: api/docker/develop/php-fpm
    volumes:
      - ./api:/app


