controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../src/Controller/Api/V1
        namespace: App\Controller\Api\V1
    prefix: /api/v1
    name_prefix: api.v1
    type: attribute

api_login_check:
    path: /api/login_check
