# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $frontendUrl: '%env(FRONTEND_URL)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Auth\Repository\UserRepositoryInterface: '@App\Auth\Repository\UserRepository'
    App\Auth\Services\HasherInterface: '@App\Auth\Services\Hasher'
    App\Auth\Services\SenderInterface: '@App\Auth\Services\Sender'
    App\Auth\Services\TokenizerInterface: '@App\Auth\Services\Tokenizer'
    App\Auth\Services\Sender:
        arguments:
            $senderEmail: '%env(TECH_EMAIL_FROM)%'
            $frontendUrl: '%env(FRONTEND_URL)%'
    App\Security\UserIdentity:
        arguments:
            $roles: []
            $id: string
            $email: string
            $passwordHash: ?string
    App\Cabinet\EventListeners\NewUserListener:
        tags: [ kernel.event_listener ]

